language: node_js

install:
  - npm install -g codecov

script:
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov

os:
  - windows
  - linux

matrix:
## An ENOMEM error occurs with 10+ under Travis-CI for Windows.
## Disable until we can determine the cause.
#  include:
#    - os: windows
#      node_js: "latest"
  exclude:
    - os: windows
      node_js: "node"
    - os: windows
      node_js: 10

node_js:
  - "node"
  - 10
  - 8
  - 6

branches:
  only:
  - master

after_success: npm run coveralls